# Generated by Django 4.2 on 2024-10-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_grade', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_language', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_price', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolQuarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_quarter', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolSuject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_suject', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(max_length=30)),
            ],
        ),
    ]
