# Generated by Django 4.2 on 2024-10-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchoolSuject',
            new_name='SchoolSubject',
        ),
        migrations.RenameField(
            model_name='schoolsubject',
            old_name='school_suject',
            new_name='school_subject',
        ),
        migrations.AlterField(
            model_name='schoolgrade',
            name='school_grade',
            field=models.IntegerField(max_length=30),
        ),
        migrations.AlterField(
            model_name='schoolprice',
            name='school_price',
            field=models.FloatField(max_length=30),
        ),
    ]
