# Generated by Django 4.2 on 2024-10-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School_data', '0002_rename_schoolsuject_schoolsubject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolgrade',
            name='school_grade',
            field=models.IntegerField(),
        ),
    ]
