# Generated by Django 4.2 on 2024-10-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School_data', '0003_alter_schoolgrade_school_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolyear',
            options={'verbose_name': '年份', 'verbose_name_plural': '年份'},
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='school_year',
            field=models.CharField(max_length=30, verbose_name='年份'),
        ),
    ]
