# Generated by Django 4.2 on 2024-10-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School_data', '0004_alter_schoolyear_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolgrade',
            options={'verbose_name': '年級', 'verbose_name_plural': '年級'},
        ),
        migrations.AlterModelOptions(
            name='schoollanguage',
            options={'verbose_name': '語言', 'verbose_name_plural': '語言'},
        ),
        migrations.AlterModelOptions(
            name='schoolprice',
            options={'verbose_name': '價錢', 'verbose_name_plural': '價錢'},
        ),
        migrations.AlterModelOptions(
            name='schoolquarter',
            options={'verbose_name': '季度', 'verbose_name_plural': '季度'},
        ),
        migrations.AlterModelOptions(
            name='schoolsubject',
            options={'verbose_name': '科目', 'verbose_name_plural': '科目'},
        ),
        migrations.AlterField(
            model_name='schoolgrade',
            name='school_grade',
            field=models.IntegerField(verbose_name='年級'),
        ),
        migrations.AlterField(
            model_name='schoollanguage',
            name='school_language',
            field=models.CharField(max_length=30, verbose_name='語言'),
        ),
        migrations.AlterField(
            model_name='schoolprice',
            name='school_price',
            field=models.FloatField(max_length=30, verbose_name='價錢'),
        ),
        migrations.AlterField(
            model_name='schoolquarter',
            name='school_quarter',
            field=models.CharField(max_length=30, verbose_name='季度'),
        ),
        migrations.AlterField(
            model_name='schoolsubject',
            name='school_subject',
            field=models.CharField(max_length=30, verbose_name='科目'),
        ),
    ]
