# Generated by Django 4.2 on 2024-10-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School_data', '0005_alter_schoolgrade_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolprice',
            name='school_price',
        ),
        migrations.AddField(
            model_name='schoolprice',
            name='hight_school_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='schoolprice',
            name='middle_school_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='schoolprice',
            name='primary_school_price',
            field=models.FloatField(default=0, verbose_name='價錢'),
        ),
    ]
