# Generated by Django 4.2 on 2024-10-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School_data', '0006_remove_schoolprice_school_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprice',
            name='hight_school_price',
            field=models.FloatField(default=0, verbose_name='高中價錢'),
        ),
        migrations.AlterField(
            model_name='schoolprice',
            name='middle_school_price',
            field=models.FloatField(default=0, verbose_name='初中價錢'),
        ),
        migrations.AlterField(
            model_name='schoolprice',
            name='primary_school_price',
            field=models.FloatField(default=0, verbose_name='小學價錢'),
        ),
    ]
