# Generated by Django 4.2 on 2024-10-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courselesson',
            options={'verbose_name': '節數', 'verbose_name_plural': '節數'},
        ),
        migrations.AlterModelOptions(
            name='courselevel',
            options={'verbose_name': '難度', 'verbose_name_plural': '難度'},
        ),
        migrations.AlterModelOptions(
            name='courseroom',
            options={'verbose_name': '課室', 'verbose_name_plural': '課室'},
        ),
        migrations.AlterModelOptions(
            name='coursetime',
            options={'verbose_name': '時間', 'verbose_name_plural': '時間'},
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='course_lesson',
            field=models.CharField(max_length=30, verbose_name='節數'),
        ),
        migrations.AlterField(
            model_name='courselevel',
            name='course_level',
            field=models.CharField(max_length=30, verbose_name='難度'),
        ),
        migrations.AlterField(
            model_name='courseroom',
            name='course_room',
            field=models.CharField(max_length=30, verbose_name='課室'),
        ),
        migrations.AlterField(
            model_name='coursetime',
            name='course_time',
            field=models.CharField(max_length=30, verbose_name='時間'),
        ),
    ]
