# Generated by Django 4.2 on 2024-10-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_branch', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolBranchArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_branch_Area', models.CharField(max_length=30)),
            ],
        ),
    ]
