# Generated by Django 4.2 on 2024-10-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_branch_campus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolbranch',
            options={'verbose_name': '分校', 'verbose_name_plural': '分校'},
        ),
        migrations.AlterModelOptions(
            name='schoolbrancharea',
            options={'verbose_name': '分校地區', 'verbose_name_plural': '分校地區'},
        ),
        migrations.AlterField(
            model_name='schoolbranch',
            name='school_branch',
            field=models.CharField(max_length=30, verbose_name='分校'),
        ),
        migrations.AlterField(
            model_name='schoolbrancharea',
            name='school_branch_Area',
            field=models.CharField(max_length=30, verbose_name='分校地區'),
        ),
    ]
