# Generated by Django 4.2 on 2024-10-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(verbose_name='權限')),
            ],
            options={
                'verbose_name': '權限',
                'verbose_name_plural': '權限',
            },
        ),
    ]
